services:
  postgres:
    container_name: postgres
    image: postgres:17 # latest is default tag, here 17 used
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscode_microservices_dev # creates initial db
      PGDATA: /data/postgres # changes default location of db files
    ports:
      - "5432:5432"
    volumes:
      - amigoscode_microservices_dev_postgres_data:/data/postgres # connect volume to the PGDATA location
      - ./docker_compose_init:/docker-entrypoint-initdb.d # creates bind mount to run init scripts
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
    command: --logging.level.zipkin2=DEBUG
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

#  eureka-server:
#    image: ihorderevtsov/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#  apigw:
#    image: ihorderevtsov/apigw:latest
#    container_name: apigw
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
  customer:
    image: ihorderevtsov/customer:latest
    container_name: customer
    ports:
      - "8010:8010"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  fraud:
    image: ihorderevtsov/fraud:latest
    container_name: fraud
    ports:
      - "8020:8020"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq
  notification:
    image: ihorderevtsov/notification:latest
    container_name: notification
    ports:
      - "8030:8030"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  amigoscode_microservices_dev_postgres_data: # creates a volume to persist data on the machine
