server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
