server:
  port: 8761
  address: 0.0.0.0
spring:
  application:
    name: eureka-server
eureka:
  client:
    # This module is a Eureka server, it does not need to register itself or fetch registry
    fetch-registry: false
    register-with-eureka: false

