services:
  postgres:
    container_name: postgres
    image: postgres:17 # latest is default tag, here 17 used
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigoscode_microservices_dev # creates initial db
      PGDATA: /data/postgres # changes default location of db files
    ports:
      - "5432:5432"
    volumes:
      - amigoscode_microservices_dev_postgres_data:/data/postgres # connect volume to the PGDATA location
      - ./docker_compose_init:/docker-entrypoint-initdb.d # creates bind mount to run init scripts
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    command: --logging.level.zipkin2=DEBUG
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge

volumes:
  amigoscode_microservices_dev_postgres_data: # creates a volume to persist data on the machine
